### ISSUE TITLE
Boostlook support and updates of antora docs

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/boostlook#13]
Multiple antora issues, fix in boostlook where possible:
1. Sidebar fonts should be condensed and vertically spaced more closely.
2. Sidebar links- remove underline, font text black, hover make blue (from standard colors)
3. Sidebar selected item - have carat text to item, without indenting item
4. Breadcrumbs - condensed font, move home icon from right to the beginning of breadcrumb.
5. Breadcrumbs missing on mobile view
6. Add "printable version"
7. Code syntax highlighting needed
8. Tables need boostlook appearance

**Comment by julioest** [comment]
@rbbeeston, can this be closed?

**Comment by rbbeeston** [comment]
completed across multiple PR's
