### ISSUE TITLE
collapse nav UI should not move when toggled

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/boostlook#14]
For the navigation visibility button:

![image](https://github.com/user-attachments/assets/5d7422fc-da90-444f-9f16-be75a25b43ef)

The collapsed / expanded version of the page should place the button in the same spot. It should be possible to click repeatedly to toggle the side nav, without moving the mouse. Let's see some proposed ideas in this issue first and then choose.

**Comment by rbbeeston** [comment]
Addressed in #22
