### ISSUE TITLE
Create adoc for boostlook testing

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/boostlook#15]
Boostlook needs a CI setup where on PR or push to master/develop it renders the sample.adoc into HTML and publishes it, so at any time we can look at the master or develop rendering and know what the latest style looks like.
`../../../b2 cxxstd=20 toolset=gcc-13 define=BOOST_CHARCONV_RUN_BENCHMARKS STL_benchmark linkflags="-lfmt" -a release .`
needs to  go into a code block and we want to see that in the sample.adoc

This sample should include all options used in the adoc.

**Comment by sdarwin** [comment]
@rbbeeston sample.adoc is input or output?   Could you provide a `preview/build.sh` script that builds what you would like to see?  What is the input, and what is the output?  Everything could go in a preview/ folder.

**Comment by vinniefalco** [comment]
if we want to do this right, there should be a Jamfile which imports the boostlook module

**Comment by sdarwin** [comment]
develop.boostlook.cpp.al
master.boostlook.cpp.al
