### ISSUE TITLE
When boostlook is moved to stage, use that to trigger moving boostlook to website-v2 develop

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/boostlook#38]
To avoid the issues we have had with updating boostlook. instead of the trigger to move from master to master, we would move from develop to develop, and then the current boostlook would go to website-v2 master during the weekly merge, avoiding any other issues.

@sdarwin this is basically what we discussed, let me know if you have additional thoughts or concerns.

**Comment by sdarwin** [comment]
if you would like to try that.

> instead of the trigger to move from master to master

( before it was triggering from master (boostlook) to develop (website-v2) and then merged weekly to master (website-v2).  )

**Comment by rbbeeston** [comment]
@sdarwin, how it was set up before would be fine, except for having to wait for a month for boostlook master to be updated during the code freeze before the release. This solution will allow continued development and merging without affecting the code freeze, and can be synced up afterwards.

**Comment by julioest** [comment]
This has been addressed – closing issue.
