### ISSUE TITLE
heading oddity

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/boostlook#42]
Noticed this in the "Any" library h1 header on stage. Seems like` #LibraryReadMe h1 a` was throwing it off with the `float:right`, can you take a look?
It should be at the top and left justified.
![Image](https://github.com/user-attachments/assets/2bc9cadc-ad53-46f6-a5de-e6c5f792fe43)

**Comment by rbbeeston** [comment]
@julioest @cdw9 we may need to figure out with boostlook what we need to keep with the #LibraryReadMe styles, and what we need to remove or move into boostlook.

**Comment by julioest** [comment]
@rbbeeston Yes, we need to eliminate (or move) styles from **website-v2** `frontend/*.css` that conflict with boostlook. Would you like @cdw9 or myself to take this on?

For this specific use case, here are the lines we're using to target the library readmes. Thankfully there's not a lot, so this would be a great place to start: https://github.com/boostorg/website-v2/blob/develop/frontend/styles.css#L99-L156

**Comment by rbbeeston** [comment]
Either one of you is fine, it's a small item, however we may want to try to either merge and/or remove that CSS completely from any boostlook styling, as it's only going to conflict. I don't want that to slow down Chrissy from what she's doing, as this is more of a maintenance task than a styling one.  So if you have the bandwidth to look at it, then go ahead, otherwise it can go to her.

**Comment by julioest** [comment]
Roger that, I'm on it!

**Comment by julioest** [comment]
The issue has been resolved. The heading is now properly aligned to the top and left justified as expected. Closing this issue.
