### ISSUE TITLE
Update GitHub Action to Trigger Action on website-v2-docs

### ISSUE THREAD

**Issue by julioest** [boostorg/boostlook#44]
Add an action that triggers a workflow in the website-v2-docs repository whenever the develop branch is updated. This ensures the latest boostlook.css is fetched automatically, keeping the website documentation consistently up-to-date with the most recent styles and changes.

**Comment by julioest** [comment]
@sdarwin How does my testing look? 

**boostlook action**
https://github.com/julioest/boostlook/actions/runs/11982192376/job/33409804607

**commit boostlook.css in website-v2** 
https://github.com/julioest/website-v2/commit/6fe928b944ff7f5732236b558434b2f13f55e10c

**website-v2-docs actions**
https://github.com/julioest/website-v2-docs/actions

**Comment by sdarwin** [comment]
Very nice!  

A few comments based on https://github.com/julioest/boostlook/blob/develop/.github/workflows/update-website-v2.yml (if that's the file being used).

`name: Install GitHub CLI` is probably not needed. The hosted runner will include `gh`.

`name: Authenticate GitHub CLI`  Perhaps can be removed also.  Earlier you had used this method which may be enough for authentication:

```
        env:
          GH_TOKEN: ${{ secrets.WEBSITE_V2_PAT }}
```

Let's try it out next week.

**Comment by sdarwin** [comment]
Edit:   those auth methods could be equally valid. So there is no preference, one or the other.
